# site settings
title: Ozan Baris Mulayim
subtitle: 
email: ozanbarismulayim@gmail.com
description: I like energy, data and all that electrifying jazz.
baseurl: "/ozanbarism.github.io" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 
city: New York
state: NY
zip_code: 10011
country: United States of America
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/ozanbarism
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: https://www.linkedin.com/in/ozanbarismulayim
  Twitter: https://twitter.com/ozanbarism
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
